function Write-LabReportMetadata {
    <#
    .SYNOPSIS
        Writes report generation metadata to analytics log for audit trail.

    .DESCRIPTION
        Write-LabReportMetadata tracks report generation events in the analytics
        log, creating an audit trail of all compliance and resource reports.
        Includes report type, format, output path, and summary statistics.

    .PARAMETER ReportType
        Type of report generated: 'Compliance' or 'Resource'.

    .PARAMETER Format
        Output format of the report: 'Console', 'Html', 'Csv', 'Json'.

    .PARAMETER OutputPath
        Path where the report file was saved (empty for Console format).

    .PARAMETER LabName
        Name of the lab the report was generated for.

    .PARAMETER Summary
        Hashtable containing summary statistics from the report.

    .PARAMETER Scheduled
        Indicates if the report was generated by a scheduled task.

    .EXAMPLE
        Write-LabReportMetadata -ReportType Compliance -Format Html -OutputPath 'report.html' -LabName 'AutomatedLab' -Summary @{ ComplianceRate = 85; TotalVMs = 3 }
        Tracks a compliance report generation event.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [ValidateSet('Compliance', 'Resource')]
        [string]$ReportType,

        [Parameter(Mandatory)]
        [ValidateSet('Console', 'Html', 'Csv', 'Json')]
        [string]$Format,

        [string]$OutputPath = '',

        [Parameter(Mandatory)]
        [string]$LabName,

        [hashtable]$Summary = @{},

        [switch]$Scheduled
    )

    try {
        $eventType = 'Report{0}' -f $ReportType

        $metadata = [ordered]@{
            Format     = $Format
            OutputPath = $OutputPath
            Scheduled  = $Scheduled
        }

        foreach ($key in $Summary.Keys) {
            $metadata[$key] = $Summary[$key]
        }

        $vmNames = @()
        if ($Summary.ContainsKey('VMs') -and $Summary.VMs -is [array]) {
            $vmNames = @($Summary.VMs | ForEach-Object { if ($_ -is [pscustomobject]) { $_.VMName } else { $_ } })
        }

        Write-LabAnalyticsEvent -EventType $eventType -LabName $LabName -VMNames $vmNames -Metadata $metadata
    }
    catch {
        Write-Warning "Write-LabReportMetadata: failed to track report metadata - $_"
    }
}
